# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: mac-test-2

on:
  push:
    branches: [ build, test ]

jobs:
  build:

    runs-on: macos-11
    environment: build
    if: "!contains(github.event.head_commit.message, '[skip test]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[skip mac]') && !contains(github.event.head_commit.message, '[skip test2]')"

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x

    # before_install:
    - run: npm i
    - run: npx playwright install chromium
    # script:
    - run: npm run build
    - run: cp .sampe.env .env

    - name: test
      uses: GabrielBB/xvfb-action@v1
      with:
        run: npm run test2 && npm run test3
      env:
        NODE_TEST: 1
        TEST_HOST: ${{ secrets.TEST_HOST }}
        TEST_USER: ${{ secrets.TEST_USER_DARWIN }}
        TEST_PASS: ${{ secrets.TEST_PASS_DARWIN }}
        GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
        GIST_ID: ${{ secrets.GIST_ID }}
        GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
        GITEE_ID: ${{ secrets.GITEE_ID }}
        CUSTOM_SYNC_URL: ${{ secrets.CUSTOM_SYNC_URL }}
        CUSTOM_SYNC_USER: ${{ secrets.CUSTOM_SYNC_USER }}
        CUSTOM_SYNC_SECRET: ${{ secrets.CUSTOM_SYNC_SECRET }}

